In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
afr = pd.read_csv("C:/Users/PROSPERITY/Documents/HamoyeDSI/FoodBalanceSheets_E_Africa_NOFLAG.csv", 
                  encoding='latin-1')
afr.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [12]:
x = afr.groupby("Area")["Y2017"].sum()
grouped = x.sort_values()
grouped

Area
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Comoros                             59.84
Seychelles                         442.34
Sao Tome and Principe            12662.63
Cabo Verde                       14650.74
Guinea-Bissau                    19102.77
Lesotho                          21267.96
Botswana                         22101.30
Djibouti                         22729.91
Gambia                           23154.18
Gabon                            27979.64
Liberia                          29342.20
Namibia                          29874.89
Central African Republic         29937.00
Congo                            41181.68
Togo                             49841.88
Mauritius                        51114.83
Eswatini                         54343.33
Sierra Leone                     55311.33
Chad                             71594.68
Rwanda                           73663.69
Zimbabwe                         75919.34
Senegal                          95681.15
Guinea                           98138.87
Burkina Faso                    101855.07
Zambia                          103223.77
Tunisia                         124167.20
Benin                           124771.22
Niger                           126707.58
Madagascar                      131197.73
Mali                            149928.33
Mauritania                      156665.46
Mozambique                      161407.98
Malawi                          181098.71
Uganda                          213950.38
CÃ´te d'Ivoire                   224599.01
Angola                          229159.57
Cameroon                        232030.43
Sudan                           239931.92
Kenya                           264660.66
United Republic of Tanzania     322616.85
Algeria                         325644.27
Ghana                           337599.06
Morocco                         388495.36
Ethiopia                        448683.76
South Africa                    517590.54
Egypt                           866379.92
Nigeria                        1483268.23
Name: Y2017, dtype: float64

In [13]:
total_null = afr["Y2014"].isnull().sum()
percent_null = (afr["Y2014"].isnull().sum())*100/len(afr["Y2014"])
print("The total number of null values is ", total_null,
      "and the percentage of null values is ",percent_null)

The total number of null values is  1589 and the percentage of null values is  2.6073544131401474

In [14]:
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]
col = ["Age","Nationality","Overall"]
df = pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])
df.head()

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [15]:
df2 = pd.DataFrame(lst, columns = col, index = [1,2,3])
df2.head()

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [16]:
afr["Area"].nunique()

49

In [17]:
afr.groupby(["Item"]).sum()

,Area Code,Area,Item Code,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,,,,
"Alcohol, Non-Food",38447,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAngo...,752497,1515090,ProductionImport QuantityStock VariationDomest...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1649136,2171381,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...,397035,90990,Food supply (kcal/capita/day)Protein supply qu...,kcal/capita/dayg/capita/dayg/capita/daykcal/ca...,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1882494,2567303,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1352989,1920418,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1518715,2275409,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...,391905,90990,Food supply (kcal/capita/day)Protein supply qu...,kcal/capita/dayg/capita/dayg/capita/daykcal/ca...,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1639683,2654934,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1319535,1818328,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaAngolaB...,970905,1525745,Export QuantityDomestic supply quantityResidua...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,200396.96,203151.78,220626.20,229174.59,221272.09

In [18]:
afr.groupby(["Element"]).sum()

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,708993,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,14197445,PopulationCereals - Excluding BeerWheat and pr...,28068795,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11840553,Cereals - Excluding BeerWheat and productsRice...,26026133,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3435732,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,3538507,Cereals - Excluding BeerWheat and productsRice...,7282199,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13285035,Cereals - Excluding BeerWheat and productsRice...,25406622,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13511060,Grand TotalVegetal ProductsAnimal ProductsCere...,3329296,kcal/capita/daykcal/capita/daykcal/capita/dayk...,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13185401,Cereals - Excluding BeerWheat and productsRice...,3163725,kgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkg...,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13795966,Cereals - Excluding BeerWheat and productsRice...,28834929,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5424803,Cereals - Excluding BeerWheat and productsRice...,10292107,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,4729749,Cereals - Excluding BeerWheat and productsStar...,8926728,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5350416,Cereals - Excluding BeerWheat and productsRice...,10313310,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,10450053,Cereals - Excluding BeerWheat and productsRice...,21388191,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3385502,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,12421089,Cereals - Excluding BeerWheat and productsRice...,24066350,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,2035933,Cereals - Excluding BeerWheat and productsRice...,4211574,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11329527,Cereals - Excluding BeerWheat and productsRice...,21464704,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,AlgeriaAngolaBeninBotswanaBurkina FasoCabo Ver...,112545,PopulationPopulationPopulationPopulationPopula...,22995,1000 persons1000 persons1000 persons1000 perso...,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,AngolaAngolaBotswanaBotswanaBotswanaBotswanaBo...,1486528,OilcropsGroundnuts (Shelled Eq)Cereals - Exclu...,2869905,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,416.00,349.00,89.00,91.00,90.00

In [19]:
afr.iloc[1:2,10:12]

   Y2017  Y2018
1    0.0    0.0

In [20]:
afr.groupby("Area")["Y2017"].sum()

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
CÃ´te d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [21]:
afr.groupby(['Area','Element']).sum()

                                                 Area Code  Item Code  \
Area     Element
Algeria  Domestic supply quantity                      464     311204
         Export Quantity                               392     264011
         Fat supply quantity (g/capita/day)            432     291489
         Feed                                           88      58967
         Food                                          420     282744
...                                                    ...        ...
Zimbabwe Protein supply quantity (g/capita/day)      20453     304589
         Residuals                                   18824     277476
         Seed                                         3439      50560
         Stock Variation                             17195     254157
         Total Population - Both sexes                 181       2501

                                                                                              Item  \
Area     Element
Algeria  Domestic supply quantity                PopulationCereals - Excluding BeerWheat and pr...
         Export Quantity                         Cereals - Excluding BeerWheat and productsRice...
         Fat supply quantity (g/capita/day)      Grand TotalVegetal ProductsAnimal ProductsCere...
         Feed                                    Cereals - Excluding BeerWheat and productsRice...
         Food                                    Cereals - Excluding BeerWheat and productsRice...
...                                                                                            ...
Zimbabwe Protein supply quantity (g/capita/day)  Grand TotalVegetal ProductsAnimal ProductsCere...
         Residuals                               Cereals - Excluding BeerWheat and productsRice...
         Seed                                    Cereals - Excluding BeerWheat and productsRice...
         Stock Variation                         Cereals - Excluding BeerWheat and productsRice...
         Total Population - Both sexes                                                  Population

                                                 Element Code  \
Area     Element
Algeria  Domestic supply quantity                      614916
         Export Quantity                               579278
         Fat supply quantity (g/capita/day)             73872
         Feed                                          121462
         Food                                          539910
...                                                       ...
Zimbabwe Protein supply quantity (g/capita/day)         76162
         Residuals                                     537680
         Seed                                          105013
         Stock Variation                               481840
         Total Population - Both sexes                    511

                                                                                              Unit  \
Area     Element
Algeria  Domestic supply quantity                1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Export Quantity                         1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Fat supply quantity (g/capita/day)      g/capita/dayg/capita/dayg/capita/dayg/capita/d...
         Feed                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Food                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
...                                                                                            ...
Zimbabwe Protein supply quantity (g/capita/day)  g/capita/dayg/capita/dayg/capita/dayg/capita/d...
         Residuals                               1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Seed                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Stock Variation                         1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
         Total Population - Both sexes                                                1000 persons

                                                    Y2014     Y2015     Y2016  \
Area     Element
Algeria  Domestic supply quantity                83755.94  85972.86  87157.61
         Export Quantity                          1328.64   1104.62   1340.22
         Fat supply quantity (g/capita/day)        320.19    317.40    309.54
         Feed                                     9656.04  10308.00   9903.00
         Food                                    60582.69  61693.49  63081.43
...                                                   ...       ...       ...
Zimbabwe Protein supply quantity (g/capita/day)    184.23    175.31    172.72
         Residuals                                -252.00   -780.00   -882.00
         Seed                                      144.00    128.00    127.00
         Stock Variation                          -644.00   -343.00    221.00
         Total Population - Both sexes           13587.00  13815.00  14030.00

                                                    Y2017     Y2018
Area     Element
Algeria  Domestic supply quantity                86810.42  90023.42
         Export Quantity                          1494.54    811.54
         Fat supply quantity (g/capita/day)        320.74    309.09
         Feed                                     9571.00  10668.00
         Food                                    62785.33  63736.33
...                                                   ...       ...
Zimbabwe Protein supply quantity (g/capita/day)    175.31    176.57
         Residuals                               -1083.00   -546.00
         Seed                                      162.00    140.00
         Stock Variation                           458.00   -447.00
         Total Population - Both sexes           14237.00  14439.00

[803 rows x 10 columns]

In [22]:
afr["Y2017"].describe()

count     59437.000000
mean        140.917765
std        1671.862359
min       -1582.000000
25%           0.000000
50%           0.100000
75%           9.000000
max      190873.000000
Name: Y2017, dtype: float64

In [23]:
numerical = ["Y2014", "Y2015", "Y2016", "Y2017"]
for i in numerical:
    print("Correlation for ", i, ":",afr["Element Code"].corr(afr[i]))

Correlation for  Y2014 : 0.024456819495221795
Correlation for  Y2015 : 0.02388919930163992
Correlation for  Y2016 : 0.023443997584961428
Correlation for  Y2017 : 0.02425400776004572

In [24]:
array1  = np.array([[94, 89, 63],[93, 92, 48],[92, 94, 56]])
arr1 = array1[:2,1:]
arr1

array([[89, 63],
       [92, 48]])

In [25]:
S = [['him', 'sell'], [90, 28, 43]]
S[0][1][1]

'e'

In [26]:
afr.groupby("Element")["Y2017"].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [27]:
y = [(2, 4), (7, 8), (1, 5, 9)]
y[1][1]

8

In [28]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment